export const CATEGORIES = {
  action: 'Екшн',
  adult: 'Для дорослих',
  adventure: 'Пригоди',
  animeComics: 'Аніме та комікси',
  arts: 'Мистецтво',
  boysLove: 'Яой',
  comedy: 'Комедія',
  drama: 'Драма',
  eastern: 'Східне',
  ecchi: 'Етті',
  fanfiction: 'Фанфікшн',
  fantasy: 'Фантастика',
  game: 'Ігри',
  genderBender: 'Зміна статі',
  girlsLove: 'Юрі',
  harem: 'Гарем',
  historical: 'Історичне',
  horror: 'Жахи',
  isekai: 'Ісєкай',
  josei: 'Дзьосей',
  lgbt: 'ЛГБТ+',
  litrpg: 'ЛітРПГ',
  magic: 'Магія',
  magicalRealism: 'Магічний реалізм',
  manhua: 'Манхуа',
  martialArts: 'Бойові мистецтва',
  mature: 'Зріле',
  mecha: 'Меха',
  military: 'Військове',
  modernLife: 'Сучасне життя',
  movies: 'Фільми',
  mystery: 'Містика',
  other: 'Інше',
  psychological: 'Психологія',
  realisticFiction: 'Реалістична фантастика',
  reincarnation: 'Реінкарнація',
  romance: 'Романтика',
  schoolLife: 'Шкільне життя',
  sciFi: 'Наукова фантастика',
  seinen: 'Сейнен',
  shoujo: 'Сьодзьо',
  shoujoAi: 'Сьодзьо-ай',
  shounen: 'Сьонен',
  shounenAi: 'Сьонен-ай',
  sliceOfLife: 'Зріз життя',
  smut: 'Смут (Еротика)',
  sports: 'Спорт',
  supernatural: 'Надприродне',
  system: 'Система',
  tragedy: 'Трагедія',
  urban: 'Міське',
  urbanLife: 'Міське життя',
  videoGames: 'Відеоігри',
  war: 'Війна',
  wuxia: 'Уся (бойові пригоди)',
  xianxia: 'Сянься',
  xuanhuan: 'Сюаньхуань',
  yaoi: 'Яой',
  yuri: 'Юрі',
};

export const genreWebn = {
  urban: 'urban-male',
  eastern: 'eastern-male',
  videoGames: 'games-male',
  fantasy: 'fantasy-male',
  scifi: 'scifi-male',
  horror: 'horror-male',
  sports: 'sports-male',
  action: 'action-male',
  war: 'war-male',
  realisticFiction: 'realistic-male',
  history: 'history-male',
  acg: 'acg-male',
  lgbt: 'lgbt-female',
  general: 'general-female',
};
